-- Criar Banco de dados
CREATE DATABASE BD_ESTACIONAMENTO
GO

-- Usa BD_ESTACIONAMENTO
USE BD_ESTACIONAMENTO
GO

-- Cria Tabelas
CREATE TABLE TB_CLIENTE(
	Id_Cliente INTEGER IDENTITY PRIMARY KEY,
	Nome_Cliente VARCHAR(50) NOT NULL,
	Carteira_Cliente VARCHAR(11) NOT NULL,
	Telefone_Cliente VARCHAR(20) NOT NULL,
	Email_Cliente VARCHAR(50) NOT NULL,
	Tipo_Cliente VARCHAR(20) NOT NULL,
	Status_Cliente CHAR(1) NOT NULL
)
GO

CREATE TABLE TB_VEICULO(
	Id_Veiculo INTEGER IDENTITY PRIMARY KEY,
	Placa_Veiculo VARCHAR(10) NOT NULL,
	Cor_Veiculo VARCHAR(11) NOT NULL,
	Modelo_Veiculo VARCHAR(15) NOT NULL,
	Tipo_Veiculo VARCHAR(10) NOT NULL,
	Status_Veiculo CHAR(1) NOT NULL
)
GO

CREATE TABLE TB_FUNCIONARIO(
	Id_Funcionario INTEGER IDENTITY PRIMARY KEY,
	Nome_Funcionario VARCHAR(50) NOT NULL,
	Cargo_Funcionario VARCHAR(10) NOT NULL,
	Matricula_Funcionario VARCHAR(15) NOT NULL,
	Status_Funcionario CHAR(1) NOT NULL
)
GO

CREATE TABLE TB_VAGA(
	Id_Vaga INTEGER IDENTITY PRIMARY KEY,
	Numero_Vaga INTEGER NOT NULL,
	Tipo_Vaga VARCHAR(20) NOT NULL,
	Status_Vaga CHAR(1) NOT NULL
)
GO

CREATE TABLE TB_TICKET(
	Id_Ticket INTEGER IDENTITY PRIMARY KEY,
	Data_Entrada_Ticket DATETIME NOT NULL,
	Data_Saida_Ticket DATETIME NOT NULL,
	Valor_Ticket DECIMAL(6, 2) NOT NULL,
	Status_Ticket CHAR(1) NOT NULL,
	Id_Cliente INTEGER NOT NULL REFERENCES TB_CLIENTE(Id_Cliente),
	Id_Funcionario INTEGER NOT NULL REFERENCES TB_FUNCIONARIO(Id_Funcionario),
	Id_Vaga INTEGER NOT NULL REFERENCES TB_VAGA(Id_Vaga),
	Id_Veiculo INTEGER NOT NULL REFERENCES TB_VEICULO(Id_Veiculo)
)
GO

CREATE TABLE TB_CAIXA(
	Id_Caixa INTEGER IDENTITY PRIMARY KEY,
	Data_Caixa DATETIME NOT NULL,
	Valor_Caixa DECIMAL(6, 2) NOT NULL,
	Forma_Pagto_Caixa VARCHAR(20) NOT NULL,
	Id_Ticket INTEGER NOT NULL REFERENCES TB_TICKET(Id_Ticket)
)
GO
