CREATE VIEW V_CONSULTA_CLIENTE AS
SELECT 
	TB_CLIENTE.Nome_Cliente,
	TB_VEICULO.Modelo_Veiculo
FROM
	TB_CLIENTE,
	TB_VEICULO,
	TB_TICKET
WHERE TB_CLIENTE.Id_Cliente = TB_TICKET.Id_Cliente
AND TB_TICKET.Id_Veiculo = TB_VEICULO.Id_Veiculo
GO

SELECT * FROM V_CONSULTA_CLIENTE
GO